/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package second_shape_drawing;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author alexf
 */
public class Second_Shape_Drawing extends javax.swing.JFrame {

    Color d;
    boolean fill;
    
    public Second_Shape_Drawing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        red = new javax.swing.JRadioButton();
        green = new javax.swing.JRadioButton();
        blue = new javax.swing.JRadioButton();
        line = new javax.swing.JRadioButton();
        oval = new javax.swing.JRadioButton();
        rectangle = new javax.swing.JRadioButton();
        scribble = new javax.swing.JRadioButton();
        filled = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        buttonGroup2.add(red);
        red.setText("Red");
        red.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                redItemStateChanged(evt);
            }
        });

        buttonGroup2.add(green);
        green.setText("Green");
        green.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                greenItemStateChanged(evt);
            }
        });

        buttonGroup2.add(blue);
        blue.setText("Blue");
        blue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blueItemStateChanged(evt);
            }
        });

        buttonGroup1.add(line);
        line.setText("Line");
        line.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lineItemStateChanged(evt);
            }
        });

        buttonGroup1.add(oval);
        oval.setText("Oval");
        oval.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ovalItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rectangle);
        rectangle.setText("Rectangle");
        rectangle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rectangleItemStateChanged(evt);
            }
        });

        buttonGroup1.add(scribble);
        scribble.setText("Scribble");
        scribble.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                scribbleItemStateChanged(evt);
            }
        });

        filled.setText("Filled");
        filled.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filledItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(green)
                    .addComponent(red)
                    .addComponent(blue))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(filled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rectangle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scribble)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(line)
                    .addComponent(oval)
                    .addComponent(rectangle)
                    .addComponent(scribble)
                    .addComponent(filled))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(red)
                        .addGap(18, 18, 18)
                        .addComponent(green)
                        .addGap(18, 18, 18)
                        .addComponent(blue))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_redItemStateChanged
        if(red.isSelected())
        {
            Color d = Color.RED;
        }
    }//GEN-LAST:event_redItemStateChanged

    private void greenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_greenItemStateChanged
        if(green.isSelected())
        {
            Color d = Color.GREEN;
        }
    }//GEN-LAST:event_greenItemStateChanged

    private void blueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blueItemStateChanged
        if(blue.isSelected())
        {
            Color d = Color.BLUE;
        }
    }//GEN-LAST:event_blueItemStateChanged

    private void filledItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filledItemStateChanged
        if(filled.isSelected())
            fill = true;
    }//GEN-LAST:event_filledItemStateChanged

    private void rectangleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rectangleItemStateChanged
        Graphics g = jPanel1.getGraphics();
        filled.setVisible(true);
        
        if(rectangle.isSelected())
            if(fill == false)
            {
                g.setColor(d);
                g.drawRect(100, 150, 125, 75);
            }
            else
            {
                g.setColor(d);
                g.fillRect(100, 150, 125, 75);
            }
            
    }//GEN-LAST:event_rectangleItemStateChanged

    private void ovalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ovalItemStateChanged
        Graphics g = jPanel1.getGraphics();
        filled.setVisible(true);
        
        if(oval.isSelected())
            if(fill == false)
            {
                g.setColor(d);
                g.drawOval(275, 150, 55, 75);
            }
            else
            {
                g.setColor(d);
                g.fillOval(275, 150, 55, 75);
            }
    }//GEN-LAST:event_ovalItemStateChanged

    private void lineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lineItemStateChanged
        Graphics g = jPanel1.getGraphics();
        filled.setVisible(false);
        
        if(line.isSelected())
        {
            g.setColor(d);
            g.drawLine(350, 300, 250, 60);
        }
    }//GEN-LAST:event_lineItemStateChanged

    private void scribbleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_scribbleItemStateChanged
        Graphics g = jPanel1.getGraphics();
        filled.setVisible(false);
        
        if(scribble.isSelected())
        {
            g.setColor(d);
            g.drawLine(200, 150, 25, 60);
            g.drawLine(25, 60, 300, 10);
        }
    }//GEN-LAST:event_scribbleItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second_Shape_Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second_Shape_Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second_Shape_Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second_Shape_Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second_Shape_Drawing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blue;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox filled;
    private javax.swing.JRadioButton green;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton line;
    private javax.swing.JRadioButton oval;
    private javax.swing.JRadioButton rectangle;
    private javax.swing.JRadioButton red;
    private javax.swing.JRadioButton scribble;
    // End of variables declaration//GEN-END:variables
}
